[package]
name = "rcoin"
version = "0.1.0"
authors = ["Hideo Hattori <hhatto.jp@gmail.com>"]

[dependencies]
rust-crypto = "0.2"
actix-web = "0.4.10"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
json = "*"
reqwest = "0.8"
